services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - elasticsearch
      - ollama
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/aiproducts
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - OLLAMA_URL=http://ollama:11434
      - GEMINI_API_KEY=AIzaSyClTVTxyvOfo1AxlIkrXkMj7apIUvPRr78
    volumes:
      - ./app:/app/app
      - ./static:/app/static
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=aiproducts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  # ---- ngrok service (new) ----
  ngrok:
    image: ngrok/ngrok:3
    depends_on:
      - app
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: >
      http
      --log=stdout
      --region=us
      app:8000
    # optional: expose ngrok web UI locally if desired (the ngrok container may or may not expose it)
    ports:
      - "4040:4040"
    restart: unless-stopped

volumes:
  postgres_data:
  elasticsearch_data:
  ollama_data:
